blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/hyunsik96/hyunsik96.github.io/discussions
    about: Ask questions and discuss with other community members
